<?php

namespace Tests\Unit\Http\Controllers;


use Tests\TestCase;

class ClientControllerTest extends TestCase
{
    with
    private $faker;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->faker = Faker\Factory::create();
    }


    public function it_can_create_a_new_infusionsoft_contact()
    {

        $contact = array(

        );

        $response = $this->withHeaders([
            'X-Header' => 'Value',
        ])->json('POST', '/user', ['name' => 'Sally']);

    }

    protected function createFakeContact(): array
    {
        return [
            'FirstName' => Faker,
            'LastName' => '',
            'Phone1' => '',
            'Email' => '',
            '_StatedIncome' => '',
            '_dob' => '',
            '_a' => '',
            'Username' => '',
            'Password' => '',
            '_ssn' => '',
            'Company' => '',
            '_Averagemonthlydepositsintobusinessbankaccount' => '',
            '_LoanAmountRequested' => '',
            '_Whatismainpurposeoffunds' => '',
            '_Bizinfo1' => '',
            '_Bizinfo2' => '',
            '_DateBusinessStarted1' => '',
            '_salesmanemail' => 'richguy@fundinghelp.com'
        ];
    }
}
